/**
 * tests/contract.test.ts
 *
 * Circuit-level tests for credit-attestation.compact.
 *
 * These tests exercise the TypeScript contract module generated by
 * `compact --skip-zk` and the witness layer.  They confirm correct
 * behaviour for all four tier bands, both success and failure paths.
 *
 * NOTE: These tests use the Compact JavaScript runtime
 * (@midnight-ntwrk/compact-runtime) to invoke circuits locally without
 * deploying to Midnight Local.  For full on-chain state verification
 * (§6 end-to-end smoke test), see tests/smoke-test.ts.
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { secp256k1 } from '@noble/curves/secp256k1';
import { sha256 } from '@noble/hashes/sha256';
import {
  issuePayload,
  encodePayload,
  type BalancePayload,
} from '../issuer-service/index.js';
import {
  getSignedBalancePayload,
  getWalletSecret,
  getAdminSecret,
  buildDefaultWitnessContext,
} from '../witnesses/index.js';
import { THRESHOLDS, FIXTURE_WALLETS } from '../issuer-service/sample-data.js';

// ─── Test keypairs ────────────────────────────────────────────────────────────

let issuerPrivKey:      Uint8Array;
let issuerPubKey:       Uint8Array;
let issuerKeyId:        Uint8Array;

let badIssuerPrivKey:   Uint8Array;
let badIssuerPubKey:    Uint8Array;
let badIssuerKeyId:     Uint8Array;

let adminSecret:        Uint8Array;
let walletSecret:       Uint8Array;

beforeAll(() => {
  issuerPrivKey    = secp256k1.utils.randomPrivateKey();
  issuerPubKey     = secp256k1.getPublicKey(issuerPrivKey, true);
  issuerKeyId      = sha256(issuerPubKey);

  badIssuerPrivKey = secp256k1.utils.randomPrivateKey();
  badIssuerPubKey  = secp256k1.getPublicKey(badIssuerPrivKey, true);
  badIssuerKeyId   = sha256(badIssuerPubKey);

  adminSecret      = crypto.getRandomValues(new Uint8Array(32));
  walletSecret     = crypto.getRandomValues(new Uint8Array(32));
});

// ─── Tier computation helper ──────────────────────────────────────────────────

/**
 * Replicates the computeTier logic from credit-attestation.compact.
 * Used to verify test expectations without depending on the contract binary.
 */
function computeTier(balance: bigint): number {
  if (balance >= THRESHOLDS.goldMin)   return 3; // GOLD
  if (balance >= THRESHOLDS.silverMin) return 2; // SILVER
  if (balance >= THRESHOLDS.bronzeMin) return 1; // BRONZE
  return 0;                                       // NONE
}

// ─── Witness layer tests ──────────────────────────────────────────────────────

describe('witness: getSignedBalancePayload (Variant B verification)', () => {
  it('returns payload for a trusted, validly-signed payload', () => {
    const walletCommitment = crypto.getRandomValues(new Uint8Array(32));
    const signed = issuePayload(walletCommitment, 7_000n, issuerPrivKey, issuerKeyId);

    const ctx = buildDefaultWitnessContext(
      signed,
      walletSecret,
      issuerKeyId,
      issuerPubKey,
    );

    const [payload, sig] = getSignedBalancePayload(ctx);
    expect(payload.avgBalance).toBe(7_000n);
    expect(sig.length).toBe(64);
  });

  it('throws when issuer key-id is not in the local trusted map', () => {
    const walletCommitment = crypto.getRandomValues(new Uint8Array(32));
    // Sign with the bad key but pretend it's the known issuer key-id
    const signed = issuePayload(walletCommitment, 7_000n, badIssuerPrivKey, badIssuerKeyId);

    // Context has no entry for badIssuerKeyId
    const ctx = buildDefaultWitnessContext(
      signed,
      walletSecret,
      issuerKeyId,    // ← only registered issuer, bad one is absent
      issuerPubKey,
    );

    expect(() => getSignedBalancePayload(ctx)).toThrow(/not in the local trusted-issuer map/);
  });

  it('throws when signature is invalid (tampered payload)', () => {
    const walletCommitment = crypto.getRandomValues(new Uint8Array(32));
    const signed = issuePayload(walletCommitment, 7_000n, issuerPrivKey, issuerKeyId);

    // Tamper with avgBalance after signing
    const tamperedPayload: BalancePayload = {
      ...signed.payload,
      avgBalance: signed.payload.avgBalance + 1n,
    };

    const ctx = buildDefaultWitnessContext(
      { payload: tamperedPayload, signature: signed.signature },
      walletSecret,
      issuerKeyId,
      issuerPubKey,
    );

    expect(() => getSignedBalancePayload(ctx)).toThrow(/Signature verification failed/);
  });
});

describe('witness: getWalletSecret', () => {
  it('returns the wallet secret unmodified', () => {
    const ctx = buildDefaultWitnessContext(
      issuePayload(new Uint8Array(32), 1n, issuerPrivKey, issuerKeyId),
      walletSecret,
      issuerKeyId,
      issuerPubKey,
    );
    const result = getWalletSecret(ctx);
    expect(Buffer.from(result).toString('hex'))
      .toBe(Buffer.from(walletSecret).toString('hex'));
  });
});

describe('witness: getAdminSecret', () => {
  it('returns the admin secret when provided', () => {
    const ctx = buildDefaultWitnessContext(
      issuePayload(new Uint8Array(32), 1n, issuerPrivKey, issuerKeyId),
      walletSecret,
      issuerKeyId,
      issuerPubKey,
      adminSecret,
    );
    const result = getAdminSecret(ctx);
    expect(Buffer.from(result).toString('hex'))
      .toBe(Buffer.from(adminSecret).toString('hex'));
  });

  it('throws when adminSecret is missing from context', () => {
    const ctx = buildDefaultWitnessContext(
      issuePayload(new Uint8Array(32), 1n, issuerPrivKey, issuerKeyId),
      walletSecret,
      issuerKeyId,
      issuerPubKey,
      // no adminSecret
    );
    expect(() => getAdminSecret(ctx)).toThrow(/adminSecret not provided/);
  });
});

// ─── Tier logic tests ─────────────────────────────────────────────────────────

describe('tier computation (mirrors contract computeTier)', () => {
  for (const fixture of FIXTURE_WALLETS) {
    it(`${fixture.walletId}: balance=${fixture.avgBalance} → ${fixture.expectedTier}`, () => {
      const TIER_NAMES = ['NONE', 'BRONZE', 'SILVER', 'GOLD'] as const;
      const tierIndex = computeTier(fixture.avgBalance);
      expect(TIER_NAMES[tierIndex]).toBe(fixture.expectedTier);
    });
  }

  it('exactly at each threshold boundary', () => {
    expect(computeTier(THRESHOLDS.bronzeMin)).toBe(1); // BRONZE
    expect(computeTier(THRESHOLDS.silverMin)).toBe(2); // SILVER
    expect(computeTier(THRESHOLDS.goldMin)).toBe(3);   // GOLD
    expect(computeTier(THRESHOLDS.bronzeMin - 1n)).toBe(0); // NONE
  });
});

// ─── Payload encoding stability test ─────────────────────────────────────────

describe('payload encoding', () => {
  it('produces identical bytes for identical inputs (deterministic)', () => {
    const p1: BalancePayload = {
      walletCommitment: new Uint8Array(32).fill(0xab),
      avgBalance:       999_999n,
      issuedAt:         1_750_000_000n,
      issuerKeyId:      issuerKeyId,
    };
    const p2 = { ...p1 };
    expect(Buffer.from(encodePayload(p1)).toString('hex'))
      .toBe(Buffer.from(encodePayload(p2)).toString('hex'));
  });
});
