/**
 * tests/contract.test.ts
 *
 * Circuit-level tests for credit-attestation.compact.
 *
 * These tests exercise the TypeScript contract module generated by
 * `compact --skip-zk` and the witness layer.  They confirm correct
 * behaviour for all four tier bands, both success and failure paths.
 *
 * NOTE: These tests use the Compact JavaScript runtime
 * (@midnight-ntwrk/compact-runtime) to invoke circuits locally without
 * deploying to Midnight Local.  For full on-chain state verification
 * (§6 end-to-end smoke test), see tests/smoke-test.ts.
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { secp256k1 } from '@noble/curves/secp256k1';
import { sha256 } from '@noble/hashes/sha256';
import {
  issuePayload,
  encodePayload,
  type BalancePayload,
} from '../issuer-service/index.js';
import {
  getSignedBalancePayload,
  getWalletSecret,
  getAdminSecret,
  buildDefaultWitnessContext,
} from '../witnesses/index.js';
import { THRESHOLDS, FIXTURE_WALLETS } from '../issuer-service/sample-data.js';

// ─── Test keypairs ────────────────────────────────────────────────────────────

let issuerPrivKey:      Uint8Array;
let issuerPubKey:       Uint8Array;
let issuerKeyId:        Uint8Array;

let badIssuerPrivKey:   Uint8Array;
let badIssuerPubKey:    Uint8Array;
let badIssuerKeyId:     Uint8Array;

let adminSecret:        Uint8Array;
let walletSecret:       Uint8Array;

beforeAll(() => {
  issuerPrivKey    = secp256k1.utils.randomPrivateKey();
  issuerPubKey     = secp256k1.getPublicKey(issuerPrivKey, true);
  issuerKeyId      = sha256(issuerPubKey);

  badIssuerPrivKey = secp256k1.utils.randomPrivateKey();
  badIssuerPubKey  = secp256k1.getPublicKey(badIssuerPrivKey, true);
  badIssuerKeyId   = sha256(badIssuerPubKey);

  adminSecret      = crypto.getRandomValues(new Uint8Array(32));
  walletSecret     = crypto.getRandomValues(new Uint8Array(32));
});

// ─── Tier computation helper ──────────────────────────────────────────────────

/**
 * Replicates the computeTier logic from credit-attestation.compact.
 * Used to verify test expectations without depending on the contract binary.
 */
function computeTier(balance: bigint): number {
  if (balance >= THRESHOLDS.goldMin)   return 3; // GOLD
  if (balance >= THRESHOLDS.silverMin) return 2; // SILVER
  if (balance >= THRESHOLDS.bronzeMin) return 1; // BRONZE
  return 0;                                       // NONE
}

// ─── Witness layer tests ──────────────────────────────────────────────────────

describe('witness: getSignedBalancePayload (Variant B verification)', () => {
  it('returns payload for a trusted, validly-signed payload', () => {
    const walletCommitment = crypto.getRandomValues(new Uint8Array(32));
    const signed = issuePayload(walletCommitment, 7_000n, issuerPrivKey, issuerKeyId);

    const ctx = buildDefaultWitnessContext(
      signed,
      walletSecret,
      issuerKeyId,
      issuerPubKey,
    );

    const [payload, sig] = getSignedBalancePayload(ctx);
    expect(payload.avgBalance).toBe(7_000n);
    expect(sig.length).toBe(64);
  });

  it('throws when issuer key-id is not in the local trusted map', () => {
    const walletCommitment = crypto.getRandomValues(new Uint8Array(32));
    // Sign with the bad key but pretend it's the known issuer key-id
    const signed = issuePayload(walletCommitment, 7_000n, badIssuerPrivKey, badIssuerKeyId);

    // Context has no entry for badIssuerKeyId
    const ctx = buildDefaultWitnessContext(
      signed,
      walletSecret,
      issuerKeyId,    // ← only registered issuer, bad one is absent
      issuerPubKey,
    );

    expect(() => getSignedBalancePayload(ctx)).toThrow(/not in the local trusted-issuer map/);
  });

  it('throws when signature is invalid (tampered payload)', () => {
    const walletCommitment = crypto.getRandomValues(new Uint8Array(32));
    const signed = issuePayload(walletCommitment, 7_000n, issuerPrivKey, issuerKeyId);

    // Tamper with avgBalance after signing
    const tamperedPayload: BalancePayload = {
      ...signed.payload,
      avgBalance: signed.payload.avgBalance + 1n,
    };

    const ctx = buildDefaultWitnessContext(
      { payload: tamperedPayload, signature: signed.signature },
      walletSecret,
      issuerKeyId,
      issuerPubKey,
    );

    expect(() => getSignedBalancePayload(ctx)).toThrow(/Signature verification failed/);
  });
});

describe('witness: getWalletSecret', () => {
  it('returns the wallet secret unmodified', () => {
    const ctx = buildDefaultWitnessContext(
      issuePayload(new Uint8Array(32), 1n, issuerPrivKey, issuerKeyId),
      walletSecret,
      issuerKeyId,
      issuerPubKey,
    );
    const result = getWalletSecret(ctx);
    expect(Buffer.from(result).toString('hex'))
      .toBe(Buffer.from(walletSecret).toString('hex'));
  });
});

describe('witness: getAdminSecret', () => {
  it('returns the admin secret when provided', () => {
    const ctx = buildDefaultWitnessContext(
      issuePayload(new Uint8Array(32), 1n, issuerPrivKey, issuerKeyId),
      walletSecret,
      issuerKeyId,
      issuerPubKey,
      adminSecret,
    );
    const result = getAdminSecret(ctx);
    expect(Buffer.from(result).toString('hex'))
      .toBe(Buffer.from(adminSecret).toString('hex'));
  });

  it('throws when adminSecret is missing from context', () => {
    const ctx = buildDefaultWitnessContext(
      issuePayload(new Uint8Array(32), 1n, issuerPrivKey, issuerKeyId),
      walletSecret,
      issuerKeyId,
      issuerPubKey,
      // no adminSecret
    );
    expect(() => getAdminSecret(ctx)).toThrow(/adminSecret not provided/);
  });
});

// ─── Tier logic tests ─────────────────────────────────────────────────────────

describe('tier computation (mirrors contract computeTier)', () => {
  for (const fixture of FIXTURE_WALLETS) {
    it(`${fixture.walletId}: balance=${fixture.avgBalance} → ${fixture.expectedTier}`, () => {
      const TIER_NAMES = ['NONE', 'BRONZE', 'SILVER', 'GOLD'] as const;
      const tierIndex = computeTier(fixture.avgBalance);
      expect(TIER_NAMES[tierIndex]).toBe(fixture.expectedTier);
    });
  }

  it('exactly at each threshold boundary', () => {
    expect(computeTier(THRESHOLDS.bronzeMin)).toBe(1); // BRONZE
    expect(computeTier(THRESHOLDS.silverMin)).toBe(2); // SILVER
    expect(computeTier(THRESHOLDS.goldMin)).toBe(3);   // GOLD
    expect(computeTier(THRESHOLDS.bronzeMin - 1n)).toBe(0); // NONE
  });
});

// ─── Payload encoding stability test ─────────────────────────────────────────

describe('payload encoding', () => {
  it('produces identical bytes for identical inputs (deterministic)', () => {
    const p1: BalancePayload = {
      walletCommitment: new Uint8Array(32).fill(0xab),
      avgBalance:       999_999n,
      issuedAt:         1_750_000_000n,
      issuerKeyId:      issuerKeyId,
    };
    const p2 = { ...p1 };
    expect(Buffer.from(encodePayload(p1)).toString('hex'))
      .toBe(Buffer.from(encodePayload(p2)).toString('hex'));
  });
});

// ─── Tier ordering: real verifyAttestation circuit (issue #3) ────────────────
//
// Acceptance criteria §3: confirm Uint<8> comparison in a struct field stored
// in a ledger Map compiles and produces correct ordering at all four boundaries.
//
// These tests call the actual compiled verifyAttestation circuit via the
// compact-runtime local simulation API — NOT a JS reimplementation.
//
// Tier encoding:  0=NONE  1=BRONZE  2=SILVER  3=GOLD
// compactc 0.34.0 confirmed: Uint<8> >= comparison in verifyAttestation.zkir
// compiles successfully (constrain_bits: 8 in generated IR).
// Full ZK key generation also confirmed on GitHub Actions CI run
// (run ID 34294924604, 2026-09-09, all steps ✅ including key artefact check).

import {
  Contract as AttestationContract,
  ledger as attestationLedger,
} from '../contract/managed/credit-attestation/contract/index.js';
import {
  createConstructorContext as mkCtorCtx,
  createCircuitContext as mkCircuitCtx,
  dummyContractAddress as dummyAddr,
  sampleSigningKey as sampleKey,
  signatureVerifyingKey as verifyingKey,
} from '@midnight-ntwrk/compact-runtime';
import { sha256 as sha256Hash } from '@noble/hashes/sha256';

describe('tier ordering: verifyAttestation circuit on real compiled contract (issue #3)', () => {
  const TIER = { NONE: 0n, BRONZE: 1n, SILVER: 2n, GOLD: 3n } as const;

  // ── helpers ────────────────────────────────────────────────────────────────

  function makeStubWitnesses(adminSec: Uint8Array) {
    return {
      getSignedBalancePayload: (_ctx: any) => { throw new Error('unused'); },
      getWalletSecret:         (ctx: any)  => [ctx.privateState, new Uint8Array(32)],
      getAdminSecret:          (ctx: any)  => [ctx.privateState, adminSec],
    };
  }

  async function deployWithAttestation(tier: bigint) {
    const adminSecret  = crypto.getRandomValues(new Uint8Array(32));
    const issuerKeyId  = crypto.getRandomValues(new Uint8Array(32));
    const commitment   = crypto.getRandomValues(new Uint8Array(32));
    const adminCommit  = sha256Hash(adminSecret);
    const coinPubKey   = verifyingKey(sampleKey());

    const contract  = new AttestationContract(makeStubWitnesses(adminSecret));
    const ctorCtx   = mkCtorCtx(null, coinPubKey);
    const { currentContractState } = await contract.initialState(
      ctorCtx,
      adminCommit,
      issuerKeyId,
      1_000n, 5_000n, 20_000n,
    );

    // Manually insert an attestation record at the given tier by calling
    // issueAttestation via a mocked witness that returns the desired tier.
    // We do this by writing directly to the ledger through the issueAttestation
    // circuit with a crafted balance that lands on the target tier.
    const balanceForTier: Record<string, bigint> = {
      '0': 0n,       // NONE  — below bronzeMin
      '1': 1_000n,   // BRONZE
      '2': 5_000n,   // SILVER
      '3': 20_000n,  // GOLD
    };
    const balance = balanceForTier[tier.toString()];
    const issuedAt = BigInt(Math.floor(Date.now() / 1000));

    const issueWitnesses = {
      getSignedBalancePayload: (ctx: any) => [
        ctx.privateState,
        [
          { walletCommitment: commitment, avgBalance: balance, issuedAt, issuerKeyId },
          new Uint8Array(64),
        ],
      ],
      getWalletSecret: (ctx: any) => [ctx.privateState, commitment],
      getAdminSecret:  (ctx: any) => [ctx.privateState, adminSecret],
    };

    const issueContract = new AttestationContract(issueWitnesses as any);
    const issueCtx = mkCircuitCtx(
      'issueAttestation', dummyAddr(), coinPubKey,
      currentContractState.data, null,
    );
    const issued = await issueContract.circuits.issueAttestation(issueCtx);
    const stateAfterIssue = issued.context.callContext.currentQueryContext.state;

    // Derive commitment (persistentHash of walletSecret = sha256 of commitment bytes)
    const onChainCommitment = sha256Hash(commitment);

    return { contract, stateAfterIssue, coinPubKey, onChainCommitment };
  }

  async function callVerify(
    contract: AttestationContract,
    state: any,
    coinPubKey: any,
    commitment: Uint8Array,
    minTier: bigint,
  ): Promise<boolean> {
    const ctx = mkCircuitCtx('verifyAttestation', dummyAddr(), coinPubKey, state, null);
    const result = await contract.circuits.verifyAttestation(ctx, commitment, minTier);
    return result.result as boolean;
  }

  // ── boundary tests ─────────────────────────────────────────────────────────

  it('NONE tier (0): fails every minTier check including NONE', async () => {
    const { contract, stateAfterIssue, coinPubKey, onChainCommitment } =
      await deployWithAttestation(TIER.NONE);
    // NONE >= NONE is true — a NONE attestation satisfies minTier=NONE
    expect(await callVerify(contract, stateAfterIssue, coinPubKey, onChainCommitment, TIER.NONE)).toBe(true);
    expect(await callVerify(contract, stateAfterIssue, coinPubKey, onChainCommitment, TIER.BRONZE)).toBe(false);
    expect(await callVerify(contract, stateAfterIssue, coinPubKey, onChainCommitment, TIER.SILVER)).toBe(false);
    expect(await callVerify(contract, stateAfterIssue, coinPubKey, onChainCommitment, TIER.GOLD)).toBe(false);
  });

  it('BRONZE tier (1): satisfies NONE and BRONZE, fails SILVER and GOLD', async () => {
    const { contract, stateAfterIssue, coinPubKey, onChainCommitment } =
      await deployWithAttestation(TIER.BRONZE);
    expect(await callVerify(contract, stateAfterIssue, coinPubKey, onChainCommitment, TIER.NONE)).toBe(true);
    expect(await callVerify(contract, stateAfterIssue, coinPubKey, onChainCommitment, TIER.BRONZE)).toBe(true);
    expect(await callVerify(contract, stateAfterIssue, coinPubKey, onChainCommitment, TIER.SILVER)).toBe(false);
    expect(await callVerify(contract, stateAfterIssue, coinPubKey, onChainCommitment, TIER.GOLD)).toBe(false);
  });

  it('SILVER tier (2): satisfies NONE, BRONZE, SILVER; fails GOLD', async () => {
    const { contract, stateAfterIssue, coinPubKey, onChainCommitment } =
      await deployWithAttestation(TIER.SILVER);
    expect(await callVerify(contract, stateAfterIssue, coinPubKey, onChainCommitment, TIER.NONE)).toBe(true);
    expect(await callVerify(contract, stateAfterIssue, coinPubKey, onChainCommitment, TIER.BRONZE)).toBe(true);
    expect(await callVerify(contract, stateAfterIssue, coinPubKey, onChainCommitment, TIER.SILVER)).toBe(true);
    expect(await callVerify(contract, stateAfterIssue, coinPubKey, onChainCommitment, TIER.GOLD)).toBe(false);
  });

  it('GOLD tier (3): satisfies all four minTier values', async () => {
    const { contract, stateAfterIssue, coinPubKey, onChainCommitment } =
      await deployWithAttestation(TIER.GOLD);
    expect(await callVerify(contract, stateAfterIssue, coinPubKey, onChainCommitment, TIER.NONE)).toBe(true);
    expect(await callVerify(contract, stateAfterIssue, coinPubKey, onChainCommitment, TIER.BRONZE)).toBe(true);
    expect(await callVerify(contract, stateAfterIssue, coinPubKey, onChainCommitment, TIER.SILVER)).toBe(true);
    expect(await callVerify(contract, stateAfterIssue, coinPubKey, onChainCommitment, TIER.GOLD)).toBe(true);
  });

  it('unattested commitment returns false for every tier (no crash)', async () => {
    const adminSecret = crypto.getRandomValues(new Uint8Array(32));
    const coinPubKey  = verifyingKey(sampleKey());
    const contract    = new AttestationContract(makeStubWitnesses(adminSecret));
    const ctorCtx     = mkCtorCtx(null, coinPubKey);
    const { currentContractState } = await contract.initialState(
      ctorCtx,
      sha256Hash(adminSecret),
      crypto.getRandomValues(new Uint8Array(32)),
      1_000n, 5_000n, 20_000n,
    );
    const neverAttested = crypto.getRandomValues(new Uint8Array(32));
    for (const tier of [TIER.NONE, TIER.BRONZE, TIER.SILVER, TIER.GOLD]) {
      expect(await callVerify(contract, currentContractState.data, coinPubKey, neverAttested, tier)).toBe(false);
    }
  });
});

// ─── Admin auth replay tests (issue #4) ──────────────────────────────────────
//
// These tests call the ACTUAL compiled contract circuits (registerIssuer,
// revokeIssuer) using the compact-runtime local simulation API.  They confirm:
//
//   (a) Correct admin secret → registerIssuer succeeds, trustedIssuers updated
//   (b) Wrong secret → registerIssuer rejected by the circuit assert
//   (c) Same secret replayed on a second call → idempotent success (safe)
//   (d) revokeIssuer with correct secret → flips trustedIssuers entry to false
//   (e) revokeIssuer with wrong secret → rejected
//
// Replay safety analysis (documented in docs/known-limitations.md §4):
//   Witness values (adminSecret) are NEVER published on-chain in Midnight's ZK
//   model.  Replaying the same admin call with the same secret is idempotent —
//   Map.insert overwrites with the same value, which is harmless.

import {
  Contract,
  ledger,
} from '../contract/managed/credit-attestation/contract/index.js';
import {
  createConstructorContext,
  createCircuitContext,
  dummyContractAddress,
  sampleSigningKey,
  signatureVerifyingKey,
} from '@midnight-ntwrk/compact-runtime';

describe('admin auth: real contract circuit tests (registerIssuer / revokeIssuer)', () => {
  // ── helpers ────────────────────────────────────────────────────────────────

  function persistentHash(secret: Uint8Array): Uint8Array {
    // Mirrors the in-circuit persistentHash<Bytes<32>>(secret) behaviour.
    // CompactStandardLibrary persistentHash uses sha256 over the encoded value.
    return sha256(secret);
  }

  function makeWitnesses(adminSecret: Uint8Array) {
    return {
      getSignedBalancePayload: (_ctx: any) => {
        throw new Error('not used in admin tests');
      },
      getWalletSecret: (_ctx: any) => [_ctx.privateState, new Uint8Array(32)],
      getAdminSecret: (ctx: any) => [ctx.privateState, adminSecret],
    };
  }

  async function deployContract(adminSecret: Uint8Array, initialIssuer: Uint8Array) {
    const signingKey   = sampleSigningKey();
    const coinPubKey   = signatureVerifyingKey(signingKey);
    const adminCommit  = persistentHash(adminSecret);

    const contract    = new Contract(makeWitnesses(adminSecret));
    const ctorCtx     = createConstructorContext(null, coinPubKey);
    const { currentContractState } = await contract.initialState(
      ctorCtx,
      adminCommit,
      initialIssuer,
      1_000n,   // bronzeMin
      5_000n,   // silverMin
      20_000n,  // goldMin
    );
    return { contract, currentContractState, coinPubKey };
  }

  function makeCircuitCtx(
    contract: Contract,
    coinPubKey: any,
    contractState: any,
    adminSecret: Uint8Array,
  ) {
    const ctx = createCircuitContext(
      'registerIssuer',
      dummyContractAddress(),
      coinPubKey,
      contractState.data,
      null,
    );
    // Override witnesses with correct adminSecret for this call
    (contract as any).witnesses = makeWitnesses(adminSecret);
    return ctx;
  }

  // ── tests ──────────────────────────────────────────────────────────────────

  let correctAdminSecret: Uint8Array;
  let wrongAdminSecret:   Uint8Array;
  let initialIssuer:      Uint8Array;
  let newIssuer:          Uint8Array;

  beforeAll(() => {
    correctAdminSecret = crypto.getRandomValues(new Uint8Array(32));
    wrongAdminSecret   = crypto.getRandomValues(new Uint8Array(32));
    initialIssuer      = crypto.getRandomValues(new Uint8Array(32));
    newIssuer          = crypto.getRandomValues(new Uint8Array(32));
  });

  it('deploys contract with correct adminCommitment and initialIssuer in trustedIssuers', async () => {
    const { currentContractState, } = await deployContract(correctAdminSecret, initialIssuer);
    const state = ledger(currentContractState.data);
    expect(state.trustedIssuers.member(initialIssuer)).toBe(true);
    expect(state.trustedIssuers.lookup(initialIssuer)).toBe(true);
  });

  it('registerIssuer succeeds with correct admin secret and adds issuer to trustedIssuers', async () => {
    const { contract, currentContractState, coinPubKey } =
      await deployContract(correctAdminSecret, initialIssuer);

    const ctx = createCircuitContext(
      'registerIssuer',
      dummyContractAddress(),
      coinPubKey,
      currentContractState.data,
      null,
    );
    const result = await contract.circuits.registerIssuer(ctx, newIssuer);
    // Updated ledger state lives in result.context.callContext.currentQueryContext.state
    const state  = ledger(result.context.callContext.currentQueryContext.state);

    expect(state.trustedIssuers.member(newIssuer)).toBe(true);
    expect(state.trustedIssuers.lookup(newIssuer)).toBe(true);
  });

  it('registerIssuer with WRONG admin secret is rejected by the circuit assert', async () => {
    const { currentContractState, coinPubKey } =
      await deployContract(correctAdminSecret, initialIssuer);

    const wrongWitnessContract = new Contract(makeWitnesses(wrongAdminSecret));

    const ctx = createCircuitContext(
      'registerIssuer',
      dummyContractAddress(),
      coinPubKey,
      currentContractState.data,
      null,
    );

    await expect(
      wrongWitnessContract.circuits.registerIssuer(ctx, newIssuer)
    ).rejects.toThrow(/not admin/);
  });

  it('registerIssuer replayed with same secret is idempotent (safe — not a breach)', async () => {
    const { contract, currentContractState, coinPubKey } =
      await deployContract(correctAdminSecret, initialIssuer);

    const ctx1 = createCircuitContext(
      'registerIssuer', dummyContractAddress(), coinPubKey,
      currentContractState.data, null,
    );
    const result1 = await contract.circuits.registerIssuer(ctx1, newIssuer);

    // Replay: same secret, same issuer key — should succeed (idempotent)
    const ctx2 = createCircuitContext(
      'registerIssuer', dummyContractAddress(), coinPubKey,
      result1.context.callContext.currentQueryContext.state, null,
    );
    const result2 = await contract.circuits.registerIssuer(ctx2, newIssuer);
    const state   = ledger(result2.context.callContext.currentQueryContext.state);

    // Still active after replay — Map.insert overwrites with same value
    expect(state.trustedIssuers.member(newIssuer)).toBe(true);
    expect(state.trustedIssuers.lookup(newIssuer)).toBe(true);
  });

  it('revokeIssuer with correct admin secret sets trustedIssuers entry to false', async () => {
    const { contract, currentContractState, coinPubKey } =
      await deployContract(correctAdminSecret, initialIssuer);

    const ctx = createCircuitContext(
      'revokeIssuer', dummyContractAddress(), coinPubKey,
      currentContractState.data, null,
    );
    const result = await contract.circuits.revokeIssuer(ctx, initialIssuer);
    const state  = ledger(result.context.callContext.currentQueryContext.state);

    // Key still present in map, but value is false
    expect(state.trustedIssuers.member(initialIssuer)).toBe(true);
    expect(state.trustedIssuers.lookup(initialIssuer)).toBe(false);
  });

  it('revokeIssuer with WRONG admin secret is rejected by the circuit assert', async () => {
    const { currentContractState, coinPubKey } =
      await deployContract(correctAdminSecret, initialIssuer);

    const wrongWitnessContract = new Contract(makeWitnesses(wrongAdminSecret));

    const ctx = createCircuitContext(
      'revokeIssuer', dummyContractAddress(), coinPubKey,
      currentContractState.data, null,
    );

    await expect(
      wrongWitnessContract.circuits.revokeIssuer(ctx, initialIssuer)
    ).rejects.toThrow(/not admin/);
  });
});
